# Generated by Django 4.1.4 on 2023-01-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_unit_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipieRequirment',
            new_name='RecipeRequirment',
        ),
    ]
